Repository taskforcehellcat/wiki, pull requests merged in 2023-06, with the labels that each got.

#80 Renew page "Funketikette"
  src/content/ausbildung/funketikette.svx
Labels: content expansion

#86 additional type safety
  src/app.d.ts
  src/lib/utils/index.ts
  src/routes/[dirslug]/[articleslug]/+layout.ts
  src/routes/[dirslug]/[articleslug]/+page.svelte
  src/routes/[dirslug]/[articleslug]/+page.ts
  src/routes/api/articles/+server.ts
Labels: enhancement

#65 Add search bar & dialog
  .mailmap
  README.md
  package-lock.json
  package.json
  src/app.d.ts
  src/app.scss
  src/content/ausbildung/steuerung.svx
  src/lib/nav/Nav.svelte
  src/lib/pickers/LayoutPicker.svelte
  src/lib/pickers/ThemePicker.svelte
  src/lib/pickers/stores.ts
  src/lib/search/.d.ts
  src/lib/search/ResultsSection.svelte
  src/lib/search/SearchModal.svelte
  src/lib/search/Searchbar.svelte
  src/lib/search/engine.ts
  src/lib/search/stores.ts
  src/lib/stores.ts
  src/lib/theme/Theme.svelte
  src/lib/utils/index.ts
  src/lib/wikitools/ExampleBox.svelte
  src/lib/wikitools/Keys.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/+page.ts
  src/routes/[dirslug]/[articleslug]/+layout.svelte
  src/routes/[dirslug]/[articleslug]/+layout.ts
  src/routes/[dirslug]/[articleslug]/+page.svelte
  src/routes/[dirslug]/[articleslug]/+page.ts
  src/routes/api/articles/+server.ts
  src/routes/api/search/+server.js
  static/fonts/fonts.css
  static/images/de.svg
  static/images/mac.svg
  static/images/us.svg
  static/images/win.svg
  tsconfig.json
Labels: enhancement, style
